### PR TITLE
fixed property-value mapping in rdfDataProvider

### LINKED ISSUE #13: The rdf example (orgOntology.ttl) does not show the values of datatype properties
properties like rdfs:comment and skos:prefLabel are blank on the canvas although there are values in the orgOntology.ttl.

I've trired figuring out where/why it's broken but not quite sure yet...

### PR DESCRIPTION
**Pull request by NielsHoffmann**
I think this should fix #13

### CODE REVIEW

**Comment by semanticfire** [comment]
Hi Niels,

Can you describe a test case ?

Bart

**Comment by NielsHoffmann** [comment]
If you start the demo server and load the rdf example then you will notice that the datatype properties are empty (rdfs:comment, or skos:prefLabel for the instance Role>Head for example)
with this fix the values will be parsed and show up in the view

**Comment by NielsHoffmann** [comment]
@semanticfire is my test case description sufficient for merging or do you need more information?

**Comment by semanticfire** [comment]
Sorry I was really busy the last couple of weeks, I'll look into it!

**Pull request merged**
